services:
     - type: web
       name: flask-ml-api
       env: python
       buildCommand: pip install -r requirements.txt
       startCommand: gunicorn app:app --timeout 120 --workers 2 --threads 2 --log-level debug
       envVars:
         - key: PYTHON_VERSION
           value: 3.10.11